# Site settings
title: "Kristy Marinaccio's Resume"
description: "My resume hosted by GitHub Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Kristy Marinaccio"
resume_title:                   "Software Engineer"
resume_contact_email:
  "marikl13@mail.buffalostate.edu"
resume_header_contact_info: "Buffalo NY | marikl13@mail.buffalostate.edu"
resume_header_intro: "<p> I am a software engineer from Buffalo NY; primarily interested in developing web services and data engineering. I excel at taking old system apart and replacing them, I also have a growing passion for InfoSec.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/KLynnM315"
  resume_twitter_url:           "https://twitter.com/kristycodes"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/kristy-marinaccio-38414110a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://jonesdeini.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
